### ISSUE TITLE
Update to 2.2.x?

### ISSUE THREAD

**Issue by matt-chan** [conda-forge/pyscf-feedstock#11]
### Comment:

Hi @BastianZim ,

Is there any chance you can bump this to 2.2.x please? I have a project that needs an updated version of pyscf.

Thanks!
Matt

**Comment by BastianZim** [comment]
Hi @matt-chan I've been slightly stuck with updating the version but I'll try to fix it when I have some more time. 
In the meanwhile, if you can make a manual PR to update it, please feel free.
