### ISSUE TITLE
might want to rebuild for libcint v6.1.2

### ISSUE THREAD

**Issue by chillenb** [conda-forge/pyscf-feedstock#29]

**Comment by BastianZim** [comment]
That should happen automatically because libcint has run exports. Let's give it a day or so.

**Comment by BastianZim** [comment]
Now in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6025

Do you know if pyscf is compatible with the new major version as well?

**Comment by chillenb** [comment]
Probably not---at least, building PySCF against libcint v6 and trying to run it against libcint v5.5 gives wrong answers without warning.

**Comment by chillenb** [comment]
There were a lot of changes from v5 to v6 including in the definition of struct CINTEnvVars
https://github.com/sunqm/libcint/commit/5c9fd6066765131e22df63412314d09f02ad4af9
I think rebuilding (and pinning libcint at ver 6) is the safe way to go.  PySCF does not include or link any numpy/python components, so also maybe conda-forge.yml and meta.yml can be changed to prevent building with multiple versions of python

**Comment by chillenb** [comment]
I constrained the libcint version in #30. Hope it builds!

**Comment by BastianZim** [comment]
Libcint has run exports which should limit the compatible versions to what is defined here: https://github.com/conda-forge/libcint-feedstock/blob/d249721e47e5b8520a39965166daaba4d11b9ee6/recipe/meta.yaml#L19

This means that no package that was built against a specific version constraint of libcint can be run against another, so what you mentioned above should not be possible. Did you try that with conda-forge built software? 

Some more info here: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#export-runtime-requirements and https://conda-forge.org/docs/maintainer/pinning_deps/#specifying-run_exports and https://conda-forge.org/docs/maintainer/pinning_deps/#updating-package-pins

Main info: https://conda-forge.org/docs/maintainer/pinning_deps/

**Comment by chillenb** [comment]
Ah nevermind, I think everything should be ok then.

Thank you for those helpful resources. I have been trying to read the documentation but my understanding is not 100%.

**Comment by BastianZim** [comment]
My pleasure! And no worries, pinning deps are one of the more complicated aspects of conda... Let me know if I can explain anything! :)
